apiVersion: v1
kind: Template
metadata:
  name: api
  annotations:
    description: sHackathon API
  labels:
    app: shackathon
    component: api

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: shackathon
        component: api
      name: api

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: shackathon
        component: api
      name: python-36-centos7-chrome

  - kind: Route
    apiVersion: v1
    metadata:
      name: api
      labels:
        app: shackathon
        component: api
    spec:
      to:
        kind: Service
        name: api

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: shackathon
        component: api
      name: api
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        service: api

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: shackathon
        component: api
      name: api
    spec:
      replicas: 1
      selector:
        service: api
      template:
        metadata:
          labels:
            service: api
        spec:
          containers:
            - name: api
              env: []
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "500m"
                limits:
                  memory: "384Mi"
                  cpu: "500m"
              readinessProbe:
                httpGet:
                  path: '/api/v1/ui'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 10
              livenessProbe:
                httpGet:
                  path: '/api/v1/ui'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 60
                timeoutSeconds: 10
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - api
            from:
              kind: ImageStreamTag
              name: 'api:latest'

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: api
      labels:
        app: shackathon
        component: api
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "api:latest"
      source:
        type: Git
        git:
          uri: https://github.com/fridex/shackathon/
          ref: master
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7-chrome:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: WEB_CONCURRENCY
              value: '4'
      triggers:
        - type: ImageChange
          imageChange: {}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: api-chrome
      labels:
        app: shackathon
        component: api
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: python-36-centos7-chrome:latest
      source:
        type: Git
        git:
          uri: https://github.com/fridex/shackathon/
          ref: master
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: WEB_CONCURRENCY
              value: '4'
      triggers:
        - type: ImageChange
          imageChange: {}


