swagger: "2.0"
info:
  title: sHackathon
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /translate:
    post:
      tags: ["Translate"]
      x-swagger-router-controller: api
      operationId: translate
      summary: Translate the given text if requested.
      parameters:
        - name: text
          in: query
          type: string
          required: true
          description: TBD.
        - name: source_lang
          in: query
          type: string
          required: false
          description: TBD.
        - name: target_lang
          in: query
          type: string
          required: false
          description: TBD.
        - name: api
          in: query
          type: string
          required: false
          description: TBD.
      responses:
        201:
          description: Translated message.

  /raw-graphql-query:
    post:
      tags: ["Translate"]
      x-swagger-router-controller: api
      operationId: raw_graphql_query
      summary: Get raw graphql query response
      parameters:
        - name: text
          in: query
          type: string
          required: true
          description: TBD.
      responses:
        201:
          description: Raw graphql response.

